{% set version = "0.1-4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-getip
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/getip_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/getip/getip_{{ version }}.tar.gz
  sha256: 63bf8528e738dbb3ecdccf6c526c40d2371cc66e7b3ccff6aaf3c4e0b569d463

build:
  merge_build_host: true  # [win]
  missing_dso_whitelist:
    - '*/R.dll'  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('getip')"           # [not win]
    - "\"%R%\" -e \"library('getip')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=getip
  license: BSD-2-Clause
  summary: A micro-package for getting your 'IP' address, either the local/internal or the public/external one. Currently only 'IPv4' addresses are supported.
  license_family: BSD
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_2_clause'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - brendanf

# Package: getip
# Type: Package
# Title: 'IP' Address 'Lookup'
# Version: 0.1-3
# Description: A micro-package for getting your 'IP' address, either the local/internal or the public/external one. Currently only 'IPv4' addresses are supported.
# License: BSD 2-clause License + file LICENSE
# Depends: R (>= 3.0.0)
# ByteCompile: yes
# Authors@R: c(person("Drew", "Schmidt", role=c("aut", "cre"), email="wrathematics@gmail.com"), person("Wei-Chen", "Chen", role="aut"))
# Maintainer: Drew Schmidt <wrathematics@gmail.com>
# RoxygenNote: 7.1.2
# NeedsCompilation: yes
# Packaged: 2023-01-23 17:13:11 UTC; mschmid3
# Author: Drew Schmidt [aut, cre], Wei-Chen Chen [aut]
# Repository: CRAN
# Date/Publication: 2023-01-25 16:50:02 UTC
